# Uncomment the next line to define a global platform for your project
source 'https://github.com/caochengfei/FFPlayer.git'
platform :ios, '9.0'

target 'FFPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FFPlayerDemo

  target 'FFPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
